# This is a basic workflow to help you get started with Actions

name: CD

on:
  # Triggers the workflow on completed CI
  workflow_run:
    workflows: ["ci"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.8.10'
          architecture: x64
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kfp
          
      - name: Install service account keys
        run: |
          echo ${{ secrets.KUBE_SERVICE_ACCOUNT }} > ~/.keys/pj-lge-ldp-kubeflow-connector.json
          export GOOGLE_APPLICATION_CREDENTIALS=~/.keys/pj-lge-ldp-kubeflow-connector.json
      - name: run pipeline to kubeflow
        run: python pipe/pipeline.py
      
